<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

In [1]:
import numpy as np

# What to expect in this chapter

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

In [2]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [3]:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

In [4]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

## 1.2 Accessing data from a list (or array)

In [5]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [6]:
py_real_names [0]

'Natasha Romanoff'

In [7]:
py_super_names[0]

'Black Widow'

In [8]:
py_super_names[2]    # Forward indexing 
                     # We need to know the size 
                     # beforehand for this to work.

'Doctor Strange'

In [9]:
py_super_names[-1]   # Reverse indexing

'Doctor Strange'

## 1.3 Accessing data from a dictionary

In [10]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}                  

In [11]:
superhero_info["Natasha Romanoff"]

'Black Widow'

In [12]:
superhero_info.keys()

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [13]:
superhero_info.values()

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

## 1.4 Higher dimensional lists

In [14]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

# 2 Lists vs. Arrays

## 2.1 Size

In [15]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

In [16]:
len(py_list_2d)

10

In [17]:
len(np_array_2d)

10

In [19]:
np_array_2d.shape

(10, 2)

## 2.2 Arrays are fussy about type

In [20]:
py_list = [1, 1.5, 'A']
np_array = np.array(py_list)

In [21]:
py_list

[1, 1.5, 'A']

In [22]:
np_array

array(['1', '1.5', 'A'], dtype='<U32')

## 2.3 Adding a number

In [23]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array

In [24]:
py_list + 10        # Won't work!

TypeError: can only concatenate list (not "int") to list

In [25]:
np_array + 10

array([11, 12, 13, 14, 15])

## 2.4 Adding another list

In [26]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [27]:
py_list_1 + py_list_2

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [28]:
np_array_1 + np_array_2

array([11, 22, 33, 44, 55])

## 2.5 Multiplying by a Number

In [29]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [30]:
py_list*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [31]:
np_array*2

array([ 2,  4,  6,  8, 10])

## 2.6 Squaring

In [32]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [33]:
py_list**2                      # Won't work!  

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [34]:
np_array**2

array([ 1,  4,  9, 16, 25])

## 2.7 Asking questions

In [36]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [37]:
py_list == 3     # Works, but what IS the question?

False

In [38]:
py_list > 3      # Won't work!

TypeError: '>' not supported between instances of 'list' and 'int'

In [39]:
np_array == 3  

array([False, False,  True, False, False])

In [40]:
np_array > 3  

array([False, False, False,  True,  True])

## 2.8 Mathematics

In [41]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [42]:
sum(py_list)     # sum() is a base Python function

15

In [43]:
max(py_list)     # max() is a base Python function

5

In [44]:
min(py_list)     # min() is a base Python function

1

In [45]:
py_list.sum()   # Won't work!

AttributeError: 'list' object has no attribute 'sum'

In [46]:
np_array.sum()

15

In [47]:
np_array.max()

5

In [48]:
np_array.min()

1

In [49]:
np_array.mean()

3.0

In [50]:
np_array.std()

1.4142135623730951

# Exercises & Self-Assessment

In [ ]:



# Your solution here




## Footnotes